### ISSUE TITLE
Neatsinaujina grafikai

### ISSUE THREAD

**Issue by Ananfred** [mpiktas/covid19lt#2]
Puslapyje - https://mpiktas.github.io/covid19lt/

Efektyvus R rodomas tik iki Sausio 4 dienos:
![image](https://user-images.githubusercontent.com/77340983/104333632-24269e80-54fa-11eb-9454-e20a257ead0f.png)

Taip pat mirčių statistikos grafikas rodomas kaip tuščias:
![image](https://user-images.githubusercontent.com/77340983/104333781-49b3a800-54fa-11eb-80a8-31abbb14f0c4.png)

**Comment by vzemlys** [comment]
Efektyvus R atsinaujina nereguliariai. Mirčių grafikai susitvarkė, problema buvo pradiniame šaltinyje
